languageCode = "en-us"
title = "Lithuania AI"
publishDir = "docs" # publish to docs for github pages compatibility
baseURL = "https://theinference.tech/"
theme = "hugo-fresh"
disableKinds = [
  "taxonomy",
  "taxonomyTerm"
]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow raw HTML rendering

[params]
  description = "Artificial Intelligence Association of Lithuania community site"
  custom_css = ["css/custom.css"]
  openGraph = true
  #section5 = true

  [params.navbarlogo]
    image = "logos/LDIA_200x50.svg"
    link = "/"

  [params.font]
    name = "Open Sans"
    sizes = [
      400.0,
      600.0
    ]

  [params.hero]
    title = "Join AI Association of Lithuania!"
    subtitle = "Community of professionals and enthusiast dedicated to artificial intelligence development in Lithuania."
    buttontext = "Join us"
    buttonlink = "/#membership"
    secbuttontext = "Learn more"
    secbuttonlink = "/#mission"
    image = "illustrations/Group_393x295.svg"
    memberlogos = [
      "Exacaster_123x70@4x",
      "NeuroTechnology_123x70@4x",
      "Oxipit_123x70@4x",
      "Pixelmator_123x70@4x",
      "Satalia_123x70@4x",
      "Unity_123x70@4x"
    ]

  [[params.navbar]]
    title = "Mission"
    url = "/#mission"

  [[params.navbar]]
    title = "Events"
    url = "/#events"

  [[params.navbar]]
    title = "Membership"
    url = "/#membership"

  [[params.navbar]]
    title = "Friends"
    url = "/#friends"

  # [[params.navbar]]
  #   title = "Contacts"
  #   url = "/"

  [params.section2]
    title = "Events"
    subtitle = "events"
    text = ""

  [params.section3]
    title = "Membership"
    subtitle = "Becoming member of AI community"
    text = "We are a not-for-profit and rely on the efforts of volunteers and support of members or patrons. Association is always looking for new people to volunteer. No previous experience in AI or development is necessary. What matters most is that you are passionate about creating or just want to know more about AI."

  [params.section4]
    title = "Friends and Partners"
    subtitle = "The companies that sponsored meetups or partnered in other ways"
    text = ""

  #   [[params.section1.tiles]]
  #     title = "App builder"
  #     icon = "mouse-globe"
  #     text = "This is some explanatory text that is on two rows"
  #     url = "/"
  #     buttonText = "Free trial"

  #   [[params.section1.tiles]]
  #     title = "Cloud integration"
  #     icon = "laptop-cloud"
  #     text = "This is some explanatory text that is on two rows"
  #     url = "/"
  #     buttonText = "Get started"

  #   [[params.section1.tiles]]
  #     title = "Add-ons & plugins"
  #     icon = "plug-cloud"
  #     text = "This is some explanatory text that is on two rows"
  #     url = "/"
  #     buttonText = "Get started"

  # [params.section2]
  #   title = "You're here because you want the best"
  #   subtitle = "And we know it"

  #   [[params.section2.features]]
  #     title = "Powerful and unified interface"
  #     text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
  #     icon = "laptop-globe"

  #   [[params.section2.features]]
  #     title = "Cross-device synchronisation"
  #     text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
  #     icon = "doc-sync"

  #   [[params.section2.features]]
  #     title = "Nomad system"
  #     text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
  #     icon = "mobile-feed"

  # [params.section3]
  #   title = "One platform"
  #   subtitle = "To rule them all"
  #   image = "illustrations/mockups/app-mockup.png"
  #   buttonText = "Get started"
  #   buttonLink = "#"

  # [params.section4]
  #   title = "Our Clients love us!"
  #   subtitle = "Lorem ipsum sit dolor amet is a dummy text used by typography industry"

  #   [[params.section4.clients]]
  #     name = "Irma Walters"
  #     quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
  #     job = "Accountant"
  #     img = 1.0

  #   [[params.section4.clients]]
  #     name = "John Bradley"
  #     quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
  #     job = "Financial Analyst"
  #     img = 2.0

  #   [[params.section4.clients]]
  #     name = "Gary Blackman"
  #     quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
  #     job = "HR Manager"
  #     img = 3.0

  [params.footer]
    logo = "LDIA_200x50_white.svg"
    socialmediatitle = "Follow Us"
    bulmalogo = false

    [params.footer.quicklinks]

      [params.footer.quicklinks.column1]
        title = "Info"

        [[params.footer.quicklinks.column1.links]]
          text = "Bylaws (in lithuanian)"
          link = "files/ldia_istatai.pdf"

        [[params.footer.quicklinks.column1.links]]
          text = "Member application form"
          link = "https://docs.google.com/forms/d/e/1FAIpQLSddLuSeS5BUFgY7RSHP1_urgg0rSALZMvL_pZicbxt-Xe4u7w/viewform"

        # [[params.footer.quicklinks.column1.links]]
        #   text = "FAQ"
        #   link = "/faq"

      [params.footer.quicklinks.column2]
        title = "Contacts"
        
        [[params.footer.quicklinks.column2.links]]
          text = "Email: info@lithuania.ai"
          link = "mailto: info@lithuania.ai"

    #     [[params.footer.quicklinks.column2.links]]
    #       text = "Get started"
    #       link = "/"

    #     [[params.footer.quicklinks.column2.links]]
    #       text = "User guides"
    #       link = "/"

    #     [[params.footer.quicklinks.column2.links]]
    #       text = "Admin guide"
    #       link = "/"

    #     [[params.footer.quicklinks.column2.links]]
    #       text = "Developers"
    #       link = "/"

    #   [params.footer.quicklinks.column3]
    #     title = "Blog"

    #     [[params.footer.quicklinks.column3.links]]
    #       text = "Latest news"
    #       link = "/blog/first"

    #     [[params.footer.quicklinks.column3.links]]
    #       text = "Tech articles"
    #       link = "/blog/second"

    [[params.footer.socialmedia]]
      link = "https://ai-lithuania.slack.com/join/shared_invite/enQtNTYzMjM3MzAwMTc4LTQ2ZGY2YTE3OWY1NjBmZWE0ZTE2NzY5OGQ5OGFkYzNkNzZjYWE4ZTEwYmZkMTM5YjRlOWI4MTE1NGNlNzAwMDU?fbclid=IwAR30mLUmQxwtltorZgb9O8aVhlE4q-9gjbeJ7l_3SCsnjO6ll8QuEY7dd0g"
      icon = "slack"

    [[params.footer.socialmedia]]
      link = "https://www.facebook.com/groups/artificialintelligence.lt/"
      icon = "facebook"

    [[params.footer.socialmedia]]
      link = "https://www.linkedin.com/company/lithuania-ai/"
      icon = "linkedin"

    [[params.footer.socialmedia]]
      link = "https://www.eventbrite.com/o/artificial-intelligence-association-of-lithuania-ldia-16793448984"
      icon = "ticket"

