languageCode = "en-us"
title = "Lithuania AI"
DefaultContentLanguage  = "en"
publishDir = "docs" # publish to docs for github pages compatibility
baseURL = "https://lithuania.ai/"
theme = "hugo-fresh"
disableKinds = [
  "taxonomy",
  "taxonomyTerm"
]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow raw HTML rendering

[params]
  description = "Artificial Intelligence Association of Lithuania community site"
  images = ["/images/logos/LDIA_600x400.png"]
  custom_css = ["css/custom.css"]
  openGraph = true
  #section5 = true

  [params.navbarlogo]
    image = "logos/LDIA_200x50.svg"
    imagelt = "logos/LDIA_Logo_LT_no_bg.svg"
    link = "/"

  [params.font]
    name = "Open Sans"
    sizes = [
      400.0,
      600.0
    ]

  [params.header]
    navbarTitle         = ""
    dynamicTitles       = false
    searchMenu          = false
    shareMenu           = false
    languageMenu        = true

  [params.hero]
    title = "Join the AI Association of Lithuania!"
    titlelt = "Junkitės į Lietuvos dirbtinio intelekto asociaciją!"    
    subtitle = "The community of professionals and enthusiasts dedicated to promoting and encouraging AI integration and development in Lithuania."
    subtitlelt = "Profesionalų ir entuziastų bendruomenė skatinanti DI taikymą, bei vystimą Lietuvoje."
    buttontext = "Join us"
    buttontextlt = "Prisijungti"    
    buttonlink = "/#membership"
    buttonlinklt = "/lt/#membership"    
    secbuttontext = "Learn more"
    secbuttontextlt = "Sužinoti daugiau"
    secbuttonlink = "/#mission"
    secbuttonlinklt = "/lt/#mission"    
    image = "illustrations/AIAL_case_2.png"
    memberlogos1 = [
      "Oxipit_123x70@4x",
      "Pixelmator_123x70@4x",
      "threethirds_123x70@4x",
      "Nascent_123x70@4x"
    ]
    memberlogos2 = [
      "Scorify_123x70@4x",
      "Vinted_123x70@4x",
      "NeuroTechnology_123x70@4x",
      "Biomatter_Desing_123x70@4x"      
    ]
    memberlogos3 = [
      "Ovoko_123x70@4x",
      "TE_123x70@4x"
    ]    

  [[params.navbar]]
    title = "Mission"
    titlelt = "Misija"    
    url = "/#mission"
    urllt = "/lt/#mission"    

  [[params.navbar]]
    title = "Events"
    titlelt = "Renginiai"    
    url = "/#events"
    urllt = "/lt/#events"

  [[params.navbar]]
    title = "Publications"
    titlelt = "Publikacijos"
    url = "/news/publications/"
    urllt = "/lt/news/publications/"

  [[params.navbar]]
    title = "Definitions"
    titlelt = "Sąvokos"
    url = "/news/definitions/"
    urllt = "/lt/news/savokos/"

  [[params.navbar]]
    title = "Membership"
    titlelt = "Narystė"    
    url = "/#membership"
    urllt = "/lt/#membership"

  [[params.navbar]]
    title = "Members"
    titlelt = "Nariai"    
    url = "https://www.notion.so/mokahaiku/Members-fd8615d1967449be8b15b04e69bcdb41"
    urllt = "https://www.notion.so/mokahaiku/Members-fd8615d1967449be8b15b04e69bcdb41"
    
  [[params.navbar]]
    title = "Friends"
    titlelt = "Draugai"    
    url = "/#friends"
    urllt = "/lt/#friends"

  [[params.navbar]]
    title = "OKRs"
    titlelt = "OKRs"
    url = "https://www.notion.so/1062403a979c4e20b9f37868221a0f63"
    urllt = "https://www.notion.so/1062403a979c4e20b9f37868221a0f63"

  [[params.navbar]]
    title = "Projects"
    titlelt = "Projektai"    
    url = "https://www.notion.so/3bb4e0947f484f0c97ee7a81f0c57ec0"
    urllt = "https://www.notion.so/3bb4e0947f484f0c97ee7a81f0c57ec0"


  [[params.navbar]]
    title = "LT"
    titlelt = "LT"    
    url = "/lt/"
    urllt = "/lt/"

  [[params.navbar]]
    title = "EN"
    titlelt = "EN"    
    url = "/en/"
    urllt = "/en"

  [params.section2]
    title = "Events"
    titlelt = "Renginiai"    
    subtitle = "events"
    text = ""

  [params.section3]
    title = "Membership"
    titlelt = "Narystė"    
    subtitle = "Becoming a member of the AI community"
    subtitlelt = "Tapimas asociacijos nariu"
    text = "We are a not-for-profit and rely on the efforts of volunteers and support of members or patrons. Association is always looking for new people to volunteer. What matters most is that you are passionate about creating or just want to know more about AI."
    textlt = "Asociacija yra ne pelno siekianti organizacija didžiąja dalimi veikianti savanorių, asociacijos narių ir remėjų pastangomis. Asociacija nuolat ieško naujų savanorių. Svarbiausia, kad turėtumėt norą kurti arba tiesiog norite sužinoti daugiau apie dirbtinį intelektą."

  #[params.section4]
  #  title = "Members of association"
  #  titlelt = "Asociacijos nariai"
  #  subtitle = "The companies that are members of Aritificial Intelligence Association of Lithuania"
  #  subtitlelt = "Įmonės ir startuoliai priklausantys Lietuvos dirbtinio intelekto asociacijai"
  #  text = ""

  [params.section5]
    title = "Friends and Partners"
    titlelt = "Asociacijos rėmėjai ir partneriai"    
    subtitle = "The organizations and associations which Aritificial Intelligence Association of Lithuania support"
    subtitlelt = "Organizacijos palaikančios Lietuvos dirbtinio intelekto asociaciją"
    text = ""


  [params.footer]
    logo = "LDIA_200x50_white.svg"
    logolt = "LDIA_200x50_white.svg"
    socialmediatitle = "Follow Us"
    socialmediatitlelt = "Sekite LDIA naujienas"    
    bulmalogo = false

    [params.footer.quicklinks]

      [params.footer.quicklinks.column1]
        title = "Info"
        titlelt = "Informacija"        

        [[params.footer.quicklinks.column1.links]]
          text = "Bylaws (in lithuanian)"
          textlt = "Įstatai"          
          link = "https://lithuania.ai/files/ldia_istatai.pdf"

        [[params.footer.quicklinks.column1.links]]
          text = "Member application form"
          textlt = "Narystės forma"          
          link = "https://docs.google.com/forms/d/e/1FAIpQLSddLuSeS5BUFgY7RSHP1_urgg0rSALZMvL_pZicbxt-Xe4u7w/viewform"

      [params.footer.quicklinks.column2]
        title = "Contacts"
        titlelt = "Kontaktai"        
        
        [[params.footer.quicklinks.column2.links]]
          text = "Email: info@lithuania.ai"
          textlt = "El. paštas: info@lithuania.ai"          
          link = "mailto: info@lithuania.ai"


    [[params.footer.socialmedia]]
      link = "https://ai-lithuania.slack.com/join/shared_invite/enQtNTYzMjM3MzAwMTc4LTQ2ZGY2YTE3OWY1NjBmZWE0ZTE2NzY5OGQ5OGFkYzNkNzZjYWE4ZTEwYmZkMTM5YjRlOWI4MTE1NGNlNzAwMDU?fbclid=IwAR30mLUmQxwtltorZgb9O8aVhlE4q-9gjbeJ7l_3SCsnjO6ll8QuEY7dd0g"
      text = "slack"

    [[params.footer.socialmedia]]
      link = "https://www.facebook.com/groups/artificialintelligence.lt/"
      text = "facebook"

    [[params.footer.socialmedia]]
      link = "https://www.linkedin.com/company/lithuania-ai/"
      text = "linkedin"

    [[params.footer.socialmedia]]
      link = "https://www.meetup.com/lithuania-ai/"
      text = "meetup"
    
    [[params.footer.socialmedia]]
      link = "https://twitter.com/lithuania_ai"
      text = "twitter"





[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.lt]
    LanguageCode        = "lt"
    LanguageName        = "Lietuvių"
    title               = "Lietuvos dirbtinio intelekto asociacija"
    weight              = 2



